# Generated by Django 5.2.4 on 2025-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='question',
            field=models.TextField(default='Unknown question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='topic',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
