# Generated by Django 5.2.4 on 2025-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_text_chatmessage_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='topic',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
