# Generated by Django 5.2.4 on 2025-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chatmessage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
